# Generated by Django 5.2.12 on 2026-04-02 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('auto_amazon', 'UserProfile')
    for u in User.objects.all():
        status = 'approved' if (u.is_active or u.is_superuser) else 'pending'
        UserProfile.objects.get_or_create(
            user_id=u.pk,
            defaults={'registration_status': status},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.RunPython(backfill_user_profiles, noop_reverse),
    ]
