# Generated by Django 5.2.12 on 2026-04-03 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_amazon', '0002_userprofile_review_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinDashboardRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('profit_margin', models.FloatField(blank=True, null=True, verbose_name='利润率(%)')),
                ('ranking_percent', models.FloatField(blank=True, null=True, verbose_name='广告难度(%)')),
                ('unit_purchase', models.FloatField(blank=True, null=True, verbose_name='单价')),
                ('monthly_results', models.FloatField(blank=True, null=True, verbose_name='体量')),
                ('profit_per_order', models.FloatField(blank=True, null=True, verbose_name='利润额')),
                ('monthly_profit1', models.FloatField(blank=True, null=True, verbose_name='产品等级(原始值)')),
                ('monthly_sales_total', models.FloatField(blank=True, null=True, verbose_name='月销售总额')),
                ('product_grade', models.CharField(max_length=1, verbose_name='产品等级')),
                ('sales_trend_json', models.TextField(blank=True, verbose_name='趋势 JSON')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='汇率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ASIN 分析行',
                'verbose_name_plural': 'ASIN 分析行',
                'ordering': ['-created_at', 'asin'],
            },
        ),
    ]
