# Generated by Django 5.2.12 on 2026-04-07 04:05

from django.conf import settings
from django.db import migrations, models


def dedupe_asin_rows(apps, schema_editor):
    """同一用户同一 ASIN 只保留 id 最大的一条，再建唯一约束。"""
    Row = apps.get_model('auto_amazon', 'AsinDashboardRow')
    seen: set[tuple[int, str]] = set()
    to_delete: list[int] = []
    for row in Row.objects.order_by('user_id', 'asin', '-id'):
        key = (row.user_id, row.asin)
        if key in seen:
            to_delete.append(row.pk)
        else:
            seen.add(key)
    if to_delete:
        Row.objects.filter(pk__in=to_delete).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auto_amazon', '0003_asin_dashboard_row'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_asin_rows, noop_reverse),
        migrations.AddConstraint(
            model_name='asindashboardrow',
            constraint=models.UniqueConstraint(
                fields=('user', 'asin'),
                name='uniq_asin_dashboard_user_asin',
            ),
        ),
    ]
