# Generated by Django 5.2.12 on 2026-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_amazon', '0004_asin_dashboard_unique_user_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='asindashboardrow',
            name='actual_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='成本'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ad_difficulty_1',
            field=models.TextField(blank=True, verbose_name='广告难度1'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ad_difficulty_2',
            field=models.TextField(blank=True, verbose_name='广告难度2'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ad_difficulty_3',
            field=models.TextField(blank=True, verbose_name='广告难度3'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ad_removed_roi',
            field=models.FloatField(blank=True, null=True, verbose_name='去广告投产比'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='head_actual_total',
            field=models.FloatField(blank=True, null=True, verbose_name='成本+头程'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='head_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='头程'),
        ),
    ]
