# Generated by Django 5.2.12 on 2026-04-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_amazon', '0005_dashboard_new_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asindashboardrow',
            name='ad_difficulty_1',
        ),
        migrations.RemoveField(
            model_name='asindashboardrow',
            name='ad_difficulty_2',
        ),
        migrations.RemoveField(
            model_name='asindashboardrow',
            name='ad_difficulty_3',
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ops_difficulty_1',
            field=models.TextField(blank=True, verbose_name='运营难度1'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ops_difficulty_2',
            field=models.TextField(blank=True, verbose_name='运营难度2'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='ops_difficulty_3',
            field=models.TextField(blank=True, verbose_name='运营难度3'),
        ),
        migrations.AddField(
            model_name='asindashboardrow',
            name='review_interval_chart_json',
            field=models.TextField(blank=True, verbose_name='评论区间图表数据 JSON'),
        ),
        migrations.AlterField(
            model_name='asindashboardrow',
            name='head_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='头程价格'),
        ),
        migrations.AlterField(
            model_name='asindashboardrow',
            name='ranking_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='广告难度'),
        ),
    ]
