# Generated by Django 5.2.12 on 2026-04-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_amazon', '0006_review_interval_ops_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asindashboardrow',
            name='review_interval_chart_json',
        ),
    ]
