"""
Django settings for auto_amazon_project project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-699nyf1=qu0=-apikwr+76t#)b67j*_n3h^x2xpc2n0cq93wl^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [item.strip() for item in _csrf_origins.split(',') if item.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_rq',
    'auto_amazon.apps.AutoAmazonConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auto_amazon.marketplace_middleware.MarketplaceRequiredMiddleware',
]

ROOT_URLCONF = 'auto_amazon_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR, 'auto_amazon/templates')
        ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'auto_amazon.context_processors.wizard_job_context',
                'auto_amazon.context_processors.marketplace_context',
                'auto_amazon.context_processors.sif_auth_alert_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto_amazon_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 兼容 Docker 场景：优先读 DB_*，缺失时回退到 MYSQL_*。
        'NAME': os.environ.get('DB_NAME') or os.environ.get('MYSQL_DATABASE', 'auto_amazon'),
        'USER': os.environ.get('DB_USER') or os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD') or os.environ.get('MYSQL_PASSWORD', '201314'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))).expanduser().resolve()

# ASIN 产品主图目录（与 media/file 同类持久化数据，部署时随 MEDIA 卷挂载即可）
# 可用环境变量 ASIN_IMAGES_ROOT 单独映射到服务器其它路径
_asin_images_env = (os.environ.get('ASIN_IMAGES_ROOT') or '').strip()
ASIN_IMAGES_ROOT = (
    Path(_asin_images_env).expanduser().resolve()
    if _asin_images_env
    else (MEDIA_ROOT / 'images')
)

# 数据审核 ZIP 导入：分片单请求体积（整包约 500MB 由多片组成，避免单次读入内存过大）
DATA_UPLOAD_MAX_MEMORY_SIZE = 64 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 64 * 1024 * 1024
# 合并后的 ZIP 总大小上限（与 media_import_staging 一致）
EXCEL_IMPORT_MAX_BYTES = 2048 * 1024 * 1024

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'select_site'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 上传分析异步任务状态（进度轮询）等。使用 Redis，多进程/多实例共享同一缓存。
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '1')
# 默认无密码；生产环境有密码时在 .env 设置 REDIS_PASSWORD
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')

_redis_options = {
    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
}
if REDIS_PASSWORD:
    _redis_options['PASSWORD'] = REDIS_PASSWORD

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
        'OPTIONS': _redis_options,
    }
}

# 定时任务（重点关注 ASIN，7 天间隔；手动计算不重置计时）
SCHEDULER_ENABLED = os.environ.get('SCHEDULER_ENABLED', 'true').lower() in ('1', 'true', 'yes', 'on')
PRIORITY_ROI_INTERVAL_DAYS = int(os.environ.get('PRIORITY_ROI_INTERVAL_DAYS', '7'))
PRIORITY_AD_INTERVAL_DAYS = int(os.environ.get('PRIORITY_AD_INTERVAL_DAYS', '7'))
# 定时批次：到期项不分散执行，统一在指定小时窗口内合并跑批（先 ROI 后广告难度）
SCHEDULER_BATCH_MODE = os.environ.get('SCHEDULER_BATCH_MODE', 'true').lower() in ('1', 'true', 'yes', 'on')
SCHEDULER_BATCH_HOUR = int(os.environ.get('SCHEDULER_BATCH_HOUR', '23'))
SCHEDULER_BATCH_WINDOW_HOURS = max(1, int(os.environ.get('SCHEDULER_BATCH_WINDOW_HOURS', '2')))
USD_CNY_RATE_FALLBACK = float(os.environ.get('USD_CNY_RATE_FALLBACK', '7.2'))
USD_CNY_RATE_CACHE_SECONDS = int(os.environ.get('USD_CNY_RATE_CACHE_SECONDS', '21600'))

# ROI 批量：单 ASIN 失败隔离与重试（阶段 A）
ROI_ASIN_MAX_RETRIES = int(os.environ.get('ROI_ASIN_MAX_RETRIES', '3'))
ROI_ASIN_RETRY_DELAY_SEC = float(os.environ.get('ROI_ASIN_RETRY_DELAY_SEC', '5'))

# RQ 任务队列（阶段 B）
# 本地 DEBUG 默认不走 RQ（无需单独开 Worker）；Docker/生产在环境变量显式设 ROI_USE_RQ=true
_roi_use_rq_raw = os.environ.get('ROI_USE_RQ')
if _roi_use_rq_raw is None:
    ROI_USE_RQ = not DEBUG
else:
    ROI_USE_RQ = _roi_use_rq_raw.lower() in ('1', 'true', 'yes', 'on')
ROI_WIZARD_EXEC_MODE = os.environ.get('ROI_WIZARD_EXEC_MODE', 'subprocess')  # worker 容器设为 inprocess
ROI_BULK_ASIN_THRESHOLD = int(os.environ.get('ROI_BULK_ASIN_THRESHOLD', '20'))
ROI_BULK_ACCOUNT_COOLDOWN_DAYS = int(os.environ.get('ROI_BULK_ACCOUNT_COOLDOWN_DAYS', '3'))
RQ_QUEUE_ROI_SINGLE = os.environ.get('RQ_QUEUE_ROI_SINGLE', 'roi_single')
RQ_QUEUE_ROI_BULK = os.environ.get('RQ_QUEUE_ROI_BULK', 'roi_bulk')
RQ_QUEUE_ROI_HIGH = os.environ.get('RQ_QUEUE_ROI_HIGH', RQ_QUEUE_ROI_SINGLE)
RQ_QUEUE_ROI_DEFAULT = os.environ.get('RQ_QUEUE_ROI_DEFAULT', 'roi_default')
RQ_QUEUE_ROI_SCHEDULED = os.environ.get('RQ_QUEUE_ROI_SCHEDULED', 'roi_scheduled')
RQ_JOB_TIMEOUT = int(os.environ.get('RQ_JOB_TIMEOUT', '86400'))  # 秒，默认 24h
ROI_SELLERSPRITE_MAX_CONCURRENT = int(os.environ.get('ROI_SELLERSPRITE_MAX_CONCURRENT', '6'))
ROI_SIF_MAX_CONCURRENT = int(os.environ.get('ROI_SIF_MAX_CONCURRENT', '4'))
ROI_TAOBAO_MAX_CONCURRENT = int(os.environ.get('ROI_TAOBAO_MAX_CONCURRENT', '1'))

_redis_url = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
if REDIS_PASSWORD:
    _redis_url = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

RQ_QUEUES = {
    RQ_QUEUE_ROI_SINGLE: {
        'URL': _redis_url,
        'DEFAULT_TIMEOUT': RQ_JOB_TIMEOUT,
    },
    RQ_QUEUE_ROI_BULK: {
        'URL': _redis_url,
        'DEFAULT_TIMEOUT': RQ_JOB_TIMEOUT,
    },
    RQ_QUEUE_ROI_HIGH: {
        'URL': _redis_url,
        'DEFAULT_TIMEOUT': RQ_JOB_TIMEOUT,
    },
    RQ_QUEUE_ROI_DEFAULT: {
        'URL': _redis_url,
        'DEFAULT_TIMEOUT': RQ_JOB_TIMEOUT,
    },
    RQ_QUEUE_ROI_SCHEDULED: {
        'URL': _redis_url,
        'DEFAULT_TIMEOUT': RQ_JOB_TIMEOUT,
    },
}
